### ISSUE TITLE
Getting compilation error "...initializer for conditional binding must have optional type.."

### ISSUE THREAD

**Issue by vikramvi** [wordpress-mobile/WordPress-iOS#7464]
### Steps to reproduce the behavior
1. Trying to compile code and getting error 
"..initializer for conditional binding must have optional type"
Refer to attached screen shot
<img width="1182" alt="screen shot 2017-06-29 at 5 03 20 pm" src="https://user-images.githubusercontent.com/308490/27694752-45a88126-5ced-11e7-9e83-213c155771a9.png">

##### Tested on [device], iOS [version], WPiOS [version]
1. Mac OS  10.12.5
2. XCode 8.3.3.

**Comment by vikramvi** [comment]
@kwonye can you please clarify how to fix this issue ?

**Comment by vikramvi** [comment]
As per my developer the code should look like below

`      guard let holder = animationHolder else {
            return
        }

        let animation = Lottie.LOTAnimationView(name: animationKey())`

**Comment by vikramvi** [comment]
ping @koke @elibud

**Comment by elibud** [comment]
@vikramvi there is an error with version 1.5.2 of the Lottie framework: https://github.com/airbnb/lottie-ios/issues/271
We recently updated the podfile: https://github.com/wordpress-mobile/WordPress-iOS/commit/8f776905ac750c3896dfde72934d3f23a4118934 and the current version of develop is working correctly on XCode 8.3.3 for me, can you pull the most recent changes, `pod install`, `clean`, and let me know how it goes?

Thanks

**Comment by vikramvi** [comment]
@elibud Thanks a ton for clarification. It fixed the issue.

**Comment by wytemusic** [comment]
@elibud Excuse me, what do I have to do now? I have Lottie 1.5.2 installed right now

**Comment by elibud** [comment]
@wytemusic please check out the latest version of develop and run 'pod install'. That will re-install Lottie 1.5.1 and the project will compile (you may need to clean + build on XCode)

**Comment by staytoooned** [comment]
I'm having the same issue and installed Lottie 1.5.2 today. How do I get Lottie 1.5.1 installed?

**Comment by elibud** [comment]
Running `pod install` in the project should sort that out @staytoooned

**Comment by staytoooned** [comment]
Thanks. Do I cd <directory of project> then pod install in the terminal?

**Comment by staytoooned** [comment]
directory of project

**Comment by elibud** [comment]
@staytoooned Yes, and you may need to clean + build on XCode

**Comment by staytoooned** [comment]
Thank you! How do I do a clean + build on Xcode?

**Comment by staytoooned** [comment]
Here is a screenshot of the project:
<img width="1129" alt="screen shot 2017-08-09 at 1 41 10 pm" src="https://user-images.githubusercontent.com/401149/29135537-79026b14-7d08-11e7-84c6-14aac4063dae.png">

**Comment by staytoooned** [comment]
I did the terminal pod install in the directory and then did a Shift-Command-K clean in my project and I'm still getting the error.

**Comment by elibud** [comment]
That project is the LottieDemo, I though you were referring to the WordPress-iOS app. The best place to get help with that is the project GitHub page: https://github.com/airbnb/lottie-ios
