### PR TITLE
Replace the Reachability Swift package with NWPathMonitor

### PR DESCRIPTION
**Pull request by crazytonyli**
## Description

The Reachability package does not compile on Xcode 26.4

```
TMReachability.m:32:9: error: Use of private header from outside its module: 'netinet6/in6.h'
```

> [!Note]
> I recommend reviewing this PR commit by commit.

### CODE REVIEW

File: Modules/Sources/WordPressShared/Reachability/ReachabilityUtils.swift [hunk 1]
```diff
@@ -1,19 +1,28 @@
...
-    public private(set) static var internetReachability: Reachability?
+    private static var pathMonitor: NWPathMonitor?
 
-    public static var connectionAvailable = false
+    /// Whether the device currently has internet connectivity.
+    ///
+    /// The initial value is `false`. After `configure()` is called, `NWPathMonitor`
+    /// updates it to the correct value on the next main run loop cycle. Subsequent
+    /// changes are pushed automatically as the network state changes.
+    public internal(set) static var connectionAvailable = false
```
Comment (crazytonyli) [inline Modules/Sources/WordPressShared/Reachability/ReachabilityUtils.swift:14]: This is a breaking change. But I don't think it'd have a real impact on the app. We should get the real value pretty quickly.

**Review by kean — APPROVED** [review]
